### ISSUE TITLE
Update "about us" page

### ISSUE THREAD

**Issue by akshayro** [Perch-UMICH/web#14]
Update about us page with:
- Organization goals (stated in our first survey)
- Diagram of our research certification 

![20171015_161053_1024](https://user-images.githubusercontent.com/22839115/31919084-2c98c7d0-b82e-11e7-9434-1e29b4f5c8f1.jpg)

**Comment by hanw-dev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add team description/goals to about us page](https://trello.com/c/xio3moyg/11-add-team-description-goals-to-about-us-page)

**Comment by hanw-dev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add advisers to about us page](https://trello.com/c/wfIvsvm9/10-add-advisers-to-about-us-page)
