### ISSUE TITLE
Lab creation page

### ISSUE THREAD

**Issue by akshayro** [Perch-UMICH/web#2]
Create view for lab creation, which only professor user types may access. Should include:

- name
- department
- description

Other considerations:
- "create lab" button on Professor user dashboard (or link to lab if created already)
- redirect to "create lab" page upon Professor account creation

**Comment by hanw-dev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement lab creation page](https://trello.com/c/aLEQAmld/6-implement-lab-creation-page)
