### ISSUE TITLE
Edit student profile page

### ISSUE THREAD

**Issue by akshayro** [Perch-UMICH/web#4]
Implement page for editing a currently existing user profile, only accessible by that user when logged in.

**Comment by wanghan03** [comment]
https://github.com/Perch-UMICH/web/commit/a786fd423dc679e92df0b2d44f016387a904875d fully implemented the ability to edit student profile page. Updating skills sections not yet implemented, waiting to see how we are handling the skills sections during registration.

**Comment by hanw-dev** [comment]
https://github.com/Perch-UMICH/web/commit/a786fd423dc679e92df0b2d44f016387a904875d fully implemented the ability to edit student profile page. Updating skills sections not yet implemented, waiting to see how we are handling the skills sections during registration.
